apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: cloudhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: lms_db
            - name: MYSQL_USER
              value: cloudhub
            - name: MYSQL_PASSWORD
              value: itverse123
          ports:
            - containerPort: 3306
