apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudhub-deployment
  namespace: cloudhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudhub
  template:
    metadata:
      labels:
        app: cloudhub
    spec:
      containers:
        - name: cloudhub
          image: yassenmeckawy74/fayen-lms:cloudhub-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cloudhub-config
            - secretRef:
                name: cloudhub-secret
          readinessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
