apiVersion: v1
kind: Service
metadata:
  name: cloudhub-service
  namespace: cloudhub
spec:
  selector:
    app: cloudhub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
