resources:
  - ../../base

namespace: cloudhub

images:
  - name: yassenmeckawy74/cloudhub
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: cloudhub-deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
